name: flex_user_agent
description: "A dart library for generating random user agents"
version: 0.0.2
repository: https://github.com/jacegem/flex_user_agent

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
